POST http://localhost:3008/user/signup
Content-Type: application/json

{
    "name": "kelllanes",
    "email": "kell@gmail.com",
    "cpf": "444.444.444-44",
    "type": "COMPRADOR"
}

//só o vendedor pode criar uma compra e  só o comprador pode fazer um pagamento

###


# @name comprador
POST http://localhost:3008/user/login
Content-Type: application/json

{
    "email": "kell@gmail.com",
    "cpf": "444.444.444-44"
}

###

//vendedor

POST http://localhost:3008/user/login
Content-Type: application/json

{
    "email": "larissa@gmail.com",
    "cpf": "111.111.111-11"
}



###
//VENDEDOR
POST http://localhost:3008/product/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkNmExMTZkLTliNTItNDVjMi05ZWY3LWRmZjc3NjliOGRiNSIsInR5cGUiOiJDT01QUkFET1IiLCJpYXQiOjE2NDg3NzUyNDEsImV4cCI6MTY0ODc3NjQ0MX0.qcM6e2qPqKeva5tnPTBM8oVBUBZGVcpFHnCthNv_J-E


{
    "seller": "Larissa",
    "title": "Escova de dentes super maneira",
    "price": "R$100,00",
    "description": "A melhor de todas as escovas"
}

###
//COMPRADOR
POST http://localhost:3008/payment/boleto
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkNmExMTZkLTliNTItNDVjMi05ZWY3LWRmZjc3NjliOGRiNSIsInR5cGUiOiJDT01QUkFET1IiLCJpYXQiOjE2NDg5NDY4NDAsImV4cCI6MTY0OTI0Njg0MH0._4n6-hxLnGOe_OrbuwOzO6HwvChD5zondlnluiZiFdU

{
        "amount": 1,
        "type": "BOLETO",
        "idProduct": "47282402-ccda-487f-b1a8-37146b7be687"
}

###


POST http://localhost:3008/payment/credit
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkNmExMTZkLTliNTItNDVjMi05ZWY3LWRmZjc3NjliOGRiNSIsInR5cGUiOiJDT01QUkFET1IiLCJpYXQiOjE2NDg5NDY4NDAsImV4cCI6MTY0OTI0Njg0MH0._4n6-hxLnGOe_OrbuwOzO6HwvChD5zondlnluiZiFdU

{       
        "idPayment": "08f5370b-960d-4378-afe8-a5c516ebc45d",
        "cardName": "Larissa Lanes",
        "cardNumber" : "1111-1111-1111-1111",
        "cardExpirationDate": "2028/10/10",
        "cardCvv": "123"
       
}



