POST http://localhost:3008/user/signup
Content-Type: application/json

{
    "name": "kelllanes",
    "email": "kell@gmail.com",
    "cpf": "444.444.444-44",
    "type": "COMPRADOR"
}

//só o vendedor pode criar uma compra e  só o comprador pode fazer um pagamento

###


# @name comprador
POST http://localhost:3008/user/login
Content-Type: application/json

{
    "email": "kell@gmail.com",
    "cpf": "444.444.444-44"
}

###

//vendedor

POST http://localhost:3008/user/login
Content-Type: application/json

{
    "email": "larissa@gmail.com",
    "cpf": "111.111.111-11"
}



###
//VENDEDOR
POST http://localhost:3008/product/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkNmExMTZkLTliNTItNDVjMi05ZWY3LWRmZjc3NjliOGRiNSIsInR5cGUiOiJDT01QUkFET1IiLCJpYXQiOjE2NDg3NzUyNDEsImV4cCI6MTY0ODc3NjQ0MX0.qcM6e2qPqKeva5tnPTBM8oVBUBZGVcpFHnCthNv_J-E


{
    "seller": "Larissa",
    "title": "Escova de dentes super maneira",
    "price": "R$100,00",
    "description": "A melhor de todas as escovas"
}

###
//COMPRADOR
POST http://localhost:3008/payment/method
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkyY2YzMWIwLWRlNDItNDdhOS04ZWU1LWZhOWJiMDBlZjRmYyIsInR5cGUiOiJWRU5ERURPUiIsImlhdCI6MTY0ODk0MDE4NywiZXhwIjoxNjQ5MjQwMTg3fQ._eOgzkE6HClfxRBDXgUuKJU_QIQ483fhEhogl-FIp5o

{
        "amount": 1,
        "type": "BOLETO",
        "idProduct": "47282402-ccda-487f-b1a8-37146b7be687"
}

###



{
     "cardName": "",
       " cardNumber" : "",
        "cardExpirationDate": "",
        "cardCvv": 
}